[tool.poetry]
name = "dataslate-parser"
version = "1.0.0"
description = "a module for parsing battlescribe rosters and allowing them to be printed or displayed cleanly"
authors = ["Steven Kessler <stvnksslr@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
beautifulsoup4 = "^4.8"
lxml = "^4.4"
weasyprint = "^50.0"
fastapi = "^0.45.0"
uvicorn = "^0.9.0"
aiofiles = "^0.4.0"
jinja2 = "^2.10"
python-multipart = "^0.0.5"
email-validator = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8"
pytest-sugar = "^0.9.2"
pep8-naming = "^0.9.0"
flake8 = "^3.7"
flake8-pytest = "^1.3"
flake8-bandit = "^2.1.2"
flake8-functions = "^0.0.2"
flake8-variables-names = "^0.0.3"
flake8-bugbear = "^19.8.0"
flake8-eradicate = "^0.2.3"
pytest-asyncio = "^0.10.0"
flake8-comprehensions = "^3.1.4"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
