[tool.poetry]
name = "dataslate-parser"
version = "1.0.0"
description = ""
authors = ["Steven Kessler <stvnksslr@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
beautifulsoup4 = "^4.7"
lxml = "^4.3"
Pillow = "^6.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
ipython = "^7.4"
pytest = "^4.4"
pytest-cov = "^2.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
