[tool.poetry]
name = "dataslate-parser"
version = "1.0.0"
description = "a module for parsing battlescribe rosters and allowing them to be printed or displayed cleanly"
authors = ["Steven Kessler <stvnksslr@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
beautifulsoup4 = "^4.8"
lxml = "^4.4"
weasyprint = "^50.0"
fastapi = "^0.40.0"
uvicorn = "^0.9.0"
aiofiles = "^0.4.0"
jinja2 = "^2.10"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.2"
pytest-cov = "^2.8"
pytest-sugar = "^0.9.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
