name: Image Build and Deploy

on:
  push:
    tags:
      - 1
      - 1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag stvnksslr/dataslate:latest
          docker push stvnksslr/dataslate:latest
