name: deploy

on:
  push:
    tags:
      - 1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        env:
          TAG_NAME: ${{ github.ref }}
        run: |
          docker login -u stvnksslr -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag stvnksslr/dataslate:$TAG_NAME
          docker push stvnksslr/dataslate:$TAG_NAMEg
